<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WinForms" Version="2.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Barber_Login_Page.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Barber_Signup_Page.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Book_Appointment_Page.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="BarberDS.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BarberDS.xsd</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="User_Home_Page.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="User_Login_Page.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="User_Signup_Page.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="connection.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="BarberDS.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>BarberDS.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>